### PR TITLE
upgrade from Play Framework 2.5.x to Play Framework 2.6.x

### PR DESCRIPTION
**Pull request by sullis**

### CODE REVIEW

**Comment by sullis** [comment]
needs QA testing

**Comment by sullis** [comment]
any progress w/ QA testing?  @kevinoriordan

**Comment by sullis** [comment]
any progress w/ QA testing?

**Comment by kevinoriordan** [comment]
was on vacation last week. Not sure this is high priority for us. Is there any particular urgency around upgrading to 2.6?

**Comment by sullis** [comment]
😄

**Pull request merged**
